const USER_ACTION_TYPES = {
  AUTH: "AUTH",
  AUTH_FAIL: "AUTH_FAIL",
  LOGOUT: "LOGOUT",
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  DELETE_PROFILE: "DELETE_PROFILE",
  START_AUTH: "START_AUTH",
};

export default USER_ACTION_TYPES;
