const TASK_ACTION_TYPES = {
  FETCH_ALL_TASKS : "FETCH_ALL_TASKS",
  CREATE_TASK : "CREATE_TASK",
  UPDATE_TASK : "UPDATE_TASK",
  DELETE_TASK : "DELETE_TASK",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING"
}

export default TASK_ACTION_TYPES